Bonjour <%= @user.first_name %> <%= @user.last_name %>,

Une erreur est survenue pendant l'import et a renvoyé ce message :
<%= @exception.message %>

La trace complète de l'erreur est jointe ci-dessous.


Notez qu'il s'agit d'un <strong>fragment de l'import </strong>qui a provoqué
cette erreur. D'autres lignes du fichier CSV ont pu déjà être importées
ou le seront dans les minutes qui viennent.

Vous recevrez un email lorsque l'ensemble de l'import s'est terminé.


Vous pouvez accéder à l'interface d'administration ici :
<%= admin_dashboard_url %>

--
L'équipe See'Up


<%= "=" * 70 %>
Trace complète de l'erreur :

<%= @exception.backtrace.join("\n") %>


<%= "=" * 70 %>
Lignes du CSV ayant provoqué cette erreur :

<%= @formatted_rows %>
